name: Convert JSON File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

#      - name: Install dependencies
#        run: npm install  # Only if you have a package.json with dependencies

      - name: Convert JSON file
        run: node scripts/convert.js

      - name: Commit converted file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generated README.md"
          git push

